#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD1B3ADC0E0238CA6 (alex.gaynor@gmail.com)
#
Name     : pretend
Version  : 1.0.9
Release  : 39
URL      : http://pypi.debian.net/pretend/pretend-1.0.9.tar.gz
Source0  : http://pypi.debian.net/pretend/pretend-1.0.9.tar.gz
Source99 : http://pypi.debian.net/pretend/pretend-1.0.9.tar.gz.asc
Summary  : A library for stubbing in Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pretend-python3
Requires: pretend-license
Requires: pretend-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
=======

%package license
Summary: license components for the pretend package.
Group: Default

%description license
license components for the pretend package.


%package python
Summary: python components for the pretend package.
Group: Default
Requires: pretend-python3

%description python
python components for the pretend package.


%package python3
Summary: python3 components for the pretend package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pretend package.


%prep
%setup -q -n pretend-1.0.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530382477
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pretend
cp LICENSE.rst %{buildroot}/usr/share/doc/pretend/LICENSE.rst
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/pretend/LICENSE.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
