#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD1B3ADC0E0238CA6 (alex.gaynor@gmail.com)
#
Name     : pretend
Version  : 1.0.9
Release  : 52
URL      : http://pypi.debian.net/pretend/pretend-1.0.9.tar.gz
Source0  : http://pypi.debian.net/pretend/pretend-1.0.9.tar.gz
Source1  : http://pypi.debian.net/pretend/pretend-1.0.9.tar.gz.asc
Summary  : A library for stubbing in Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pretend-license = %{version}-%{release}
Requires: pretend-python = %{version}-%{release}
Requires: pretend-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
=======

%package license
Summary: license components for the pretend package.
Group: Default

%description license
license components for the pretend package.


%package python
Summary: python components for the pretend package.
Group: Default
Requires: pretend-python3 = %{version}-%{release}

%description python
python components for the pretend package.


%package python3
Summary: python3 components for the pretend package.
Group: Default
Requires: python3-core
Provides: pypi(pretend)

%description python3
python3 components for the pretend package.


%prep
%setup -q -n pretend-1.0.9
cd %{_builddir}/pretend-1.0.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1603399221
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pretend
cp %{_builddir}/pretend-1.0.9/LICENSE.rst %{buildroot}/usr/share/package-licenses/pretend/b8244d638801c0e229ef021afd04594e09f113f3
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pretend/b8244d638801c0e229ef021afd04594e09f113f3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
